server:
  port: ${PORT:0}
#  servlet:
#    context-path: /account-app
spring:
  application:
    name: banking-app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url:
        - http://localhost:8888/admin
        instance:
          service-base-url: http://localhost:8888/admin
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://3.239.41.234:3307/hr
    password: root
    username: root
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
